hailomz compile --ckpt /ailab_mat2/dataset/drone/250312_sejong/yolo_weights/250724_yolov5/pth_sources/yolov5m_3class_250725/weights/best.onnx --calib-path /media/jemo/HDD1/Workspace/dset/Drone-Detection-Custom/250312_sejong/yolo_dataset/images/calib --yaml /media/jemo/HDD1/Workspace/src/Project/Drone24/edgeboard/Imx/yolov5/hef_convert_yaml/custom_yolov5m_3class.yaml --classes 3 --hw-arch hailo8
hailomz compile --ckpt /ailab_mat2/dataset/drone/250312_sejong/yolo_weights/250724_yolov5/pth_sources/yolov5n_3class_250725/weights/best.onnx --calib-path /media/jemo/HDD1/Workspace/dset/Drone-Detection-Custom/250312_sejong/yolo_dataset/images/calib --yaml /media/jemo/HDD1/Workspace/src/Project/Drone24/edgeboard/Imx/yolov5/hef_convert_yaml/custom_yolov5n_3class.yaml --classes 3 --hw-arch hailo8
hailomz compile --ckpt /ailab_mat2/dataset/drone/250312_sejong/yolo_weights/250724_yolov5/pth_sources/yolov5s_3class_250725/weights/best.onnx --calib-path /media/jemo/HDD1/Workspace/dset/Drone-Detection-Custom/250312_sejong/yolo_dataset/images/calib --yaml /media/jemo/HDD1/Workspace/src/Project/Drone24/edgeboard/Imx/yolov5/hef_convert_yaml/custom_yolov5s_3class.yaml --classes 3 --hw-arch hailo8
hailomz compile --ckpt /ailab_mat2/dataset/drone/250312_sejong/yolo_weights/250724_yolov5/pth_sources/yolov5m_10class_250725/weights/best.onnx --calib-path /media/jemo/HDD1/Workspace/dset/Drone-Detection-Custom/250312_sejong/yolo_dataset/images/calib --yaml /media/jemo/HDD1/Workspace/src/Project/Drone24/edgeboard/Imx/yolov5/hef_convert_yaml/custom_yolov5m_10class.yaml --classes 10 --hw-arch hailo8
hailomz compile --ckpt /ailab_mat2/dataset/drone/250312_sejong/yolo_weights/250724_yolov5/pth_sources/yolov5n_10class_250725/weights/best.onnx --calib-path /media/jemo/HDD1/Workspace/dset/Drone-Detection-Custom/250312_sejong/yolo_dataset/images/calib --yaml /media/jemo/HDD1/Workspace/src/Project/Drone24/edgeboard/Imx/yolov5/hef_convert_yaml/custom_yolov5n_10class.yaml --classes 10 --hw-arch hailo8
hailomz compile --ckpt /ailab_mat2/dataset/drone/250312_sejong/yolo_weights/250724_yolov5/pth_sources/yolov5s_10class_250725/weights/best.onnx --calib-path /media/jemo/HDD1/Workspace/dset/Drone-Detection-Custom/250312_sejong/yolo_dataset/images/calib --yaml /media/jemo/HDD1/Workspace/src/Project/Drone24/edgeboard/Imx/yolov5/hef_convert_yaml/custom_yolov5s_10class.yaml --classes 10 --hw-arch hailo8




----
 hailomz parse --ckpt /ailab_mat2/dataset/drone/250312_sejong/yolo_weights/250724_yolov5/pth_sources/yolov5m_3class_250725/weights/best.onnx  --yaml /media/jemo/HDD1/Workspace/src/Project/Drone24/edgeboard/Imx/yolov5/hef_convert_yaml/custom_yolov5m_3class.yaml
